# Generated by Django 4.0.3 on 2022-03-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='slug',
        ),
        migrations.AlterField(
            model_name='bug',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
